spring:
  cloud:
    gcp:
      sql:
        enabled: true
        database-name: prueba-tecnica
        instance-connection-name: glossy-buffer-441215-h9:us-central1:prueba-java
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
    username: 'java'
    password: ']}R:%dGQ?bzP~CX>'
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect