# curl --request DELETE
#  --url http://localhost:8080/product
#  --header 'Content-Type: application/json'
#  --header 'User-Agent: insomnia/10.0.0'
#  --data '{"franchiseName":"Starbucks", "branchName":"Jardín chipichape", "name": "Pan"}'
DELETE http://localhost:8080/product
User-Agent: insomnia/10.0.0
Content-Type: application/json

{
  "franchiseName": "Starbucks",
  "branchName": "Jardín chipichape",
  "name": "Pan"
}

###

