# curl --request POST
#  --url http://localhost:8080/franchise
#  --header 'Content-Type: application/json'
#  --header 'User-Agent: insomnia/10.0.0'
#  --data '{"name":"Adidas"}'
POST http://localhost:8080/franchise
User-Agent: insomnia/10.0.0
Content-Type: application/json

{
  "name": "Adidas"
}

###

